### ISSUE TITLE
cmdlnprint blocks e10s rollout

### ISSUE THREAD

**Issue by bdurrow** [eclipxe13/cmdlnprint#12]
Add-on {243cc1ee-c821-4544-aebb-54c44125b9aa} blocks e10s rollout.

I think this indicates that the plugin will be disabled on e10s builds soon.

**Comment by eclipxe13** [comment]
As far I could see about [e10s](https://wiki.mozilla.org/Electrolysis#Overview) in the site [Are we e10s yet?](https://arewee10syet.com/#124) cmdlnprint is mark as compatible.

I may not be compatible before in the past but I changed the plugin to avoid deprecated methods.
The mozilla addons page shows it as: Add-on Multi Process Status: Compatible.

> Add-on {243cc1ee-c821-4544-aebb-54c44125b9aa} blocks e10s rollout.

Could you please provide more information ?

**Comment by bdurrow** [comment]
I'll gather more information.  This is just something I see in the output while testing with travis-ci.

**Comment by bdurrow** [comment]
Okay after digging I found that cmdlnprint isn't whitelisted here: https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/E10SAddonsRollout.jsm; the reason is given in this comment:

> // ================== ADDONS FOR 51 RELEASE ==================
//
// During the 51 beta cycle, we tested e10s with all addons
// except those explicitly marked as being incompatible.
// For release, instead of opening this up, we assembled
// the lists below with all addons that were seen on beta
// and had over 50 installs.
//
// This list is in a new format to allow fast access and also
// to allow controlling by the number of addons installed.
