### ISSUE TITLE
Not working when run from a script on cron

### ISSUE THREAD

**Issue by brailateo** [eclipxe13/cmdlnprint#13]
Error: GDK_BACKEND does not match available displays

The same script works fine when run in bash in a terminal.
A window containing the HTML page is flashing , then a progress window for printing is shown for 2-3 seconds.

Is there a chance to run it --headless ?

The quick workaround is to install Xvfb and run in script with:

`/usr/bin/xvfb-run /usr/bin/firefox -print "http://....html" -print-mode pdf  . . .`

Teo

**Comment by eclipxe13** [comment]
No. There is no way to run without X.
However, You can run it using xvfb or start a vnc server and run the printing inside passing the DISPLAY variable.
