### ISSUE TITLE
Problem on Linux: Failed to open curl lib from binary, use libcurl.so instead

### ISSUE THREAD

**Issue by wellington1993** [eclipxe13/cmdlnprint#19]
Hi,

I have problems with this extension on latest Firefox at Linux:
The error: Failed to open curl lib from binary, use libcurl.so instead

```
Failed to open curl lib from binary, use libcurl.so instead
ExceptionHandler::GenerateDump cloned child 339
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal..
```

Thanks...

**Comment by eclipxe13** [comment]
This library does not use curl or libcurl by its own. I really doubt that the problem is related to this.
Could you please provide more information about your OS, Firefox installation and simple test agains wikipedia or other public site?

PS: Sorry for the late response.

**Comment by wellington1993** [comment]
@eclipxe13 I don't know the source too.
Thanks for the help.
:+1:
