### ISSUE TITLE
Please add support for printing via command line argument for Firefox 57+

### ISSUE THREAD

**Issue by MurzNN** [eclipxe13/cmdlnprint#23]
Thanks, very useful extension, but it stops working on Firefox 57+. Can you port it to WebExtensions?
Also I create a feature request in Firefox bug tracker https://bugzilla.mozilla.org/show_bug.cgi?id=1407238 - maybe they integrate this feature in Firefox.

**Comment by MurzNN** [comment]
Seems Mozilla accept the issue with P3!

**Comment by eclipxe13** [comment]
Very nice! If there is a WebExtension I would be glad to create a new plugin.

In the mean time you can use docker to print using an old version of Firefox with this plugin, and don't mess up with your working environment.

https://github.com/eclipxe13/cmdlnprint/blob/master/docker/README.md

I had review other alternatives but they did not provide the minimal options like margins, headers, footers, etc...

**Comment by Kurara** [comment]
Ey, I have one question. I tried to install an old version of firefox https://ftp.mozilla.org/pub/firefox/releases/56.0/ but when I try to install the plugin it says your browser doesn't support. Exactily which version should I download? I saw the solution of your docker, but I would like to have an old version of firefox installed anyway.
