### ISSUE TITLE
Print to png file options doesnt work - windows 7 and firefox 50

### ISSUE THREAD

**Issue by ndinev** [eclipxe13/cmdlnprint#6]
However print to pdf seems to work

**Comment by eclipxe13** [comment]
I think this will be fixed with the last update, once I see the plugin is published I will tested under a windows 10 machine, I don't have more windows versions to test but I really appreciate if you can test it in your environment.

**Comment by eclipxe13** [comment]
I had tested on Windows 10, Firefox 51.0.1 and cmdlnprint 1.0.3 and the PNG file was created.

Could somebody confirm that this works on other windows versions?

Thanks in advance!

**Comment by eclipxe13** [comment]
I will close this issue, If you found that is not creating a PNG file please open another issue.
