### ISSUE TITLE
[GFX1-]: D3D11 layers just crashed; D3D11 will be disabled.

### ISSUE THREAD

**Issue by MikeNebgen** [eclipxe13/cmdlnprint#7]
This seems to only work for me once, then Firefox hangs and cmdlnprint won't run again until I reboot or do some serious clean-up.  I get the error message: [GFX1-]: D3D11 layers just crashed; D3D11 will be disabled. ...then on subsequent runs, I get: [GFX1-]: D3D11 layers disabled due to a prior crash. but at lease it allows Firefox to close.  In this case, the resulting PDF is unreadable by any viewer.  I'm running Firefox v51.0.1 (32-bit).  This happens from both the command line and a task scheduled .bat or .cmd file.

**Comment by MikeNebgen** [comment]
Ok, this can be fixed by disabling the hardware acceleration in the Firefox settings.

**Comment by eclipxe13** [comment]
Thanks for your comment, I will ad this note on README file
