### ISSUE TITLE
Header and Footer options don't appear to do anything

### ISSUE THREAD

**Issue by bdurrow** [eclipxe13/cmdlnprint#8]
Tested with FF51 When I have prefs.js with settings like this:
```
user_pref("print.print_footerleft", "");
user_pref("print.print_footerright", "");
user_pref("print.print_headerleft", "");
user_pref("print.print_headerright", "");
```
and I print with -print-footer-left left -print-footer-right right, I expect there to be a footer but I don't see one.

In FF11 the problem is worse as I can't turn off the default headers and footers with any combination of command line arguments or prefs.js modifications.  I tested FF11 in Ubuntu trusty and centos 6.

**Comment by eclipxe13** [comment]
Could you please provide me the exact command you are using?

**Comment by bdurrow** [comment]
### Short answer:
```
firefox -print https://google.com -print-footer-left left -print-footer-right right -print-mode pdf -print-file /home/firefox/google.pdf
```

For the exact method of testing please see the notes I added to [Issue 9](https://github.com/eclipxe13/cmdlnprint/issues/9).  

### Run commands:
```
for ff_version in 11 51; do 
  ff_home=`pwd`/ff-home-${ff_version}
  mkdir ${ff_home}; rm ${ff_home}/google.pdf
  docker run --rm --volume ${ff_home}:/home/firefox \
    -e "DISPLAY=${DOCKER_DISPLAY}" \
    -u `id -u` \
    -e 'HOME=/home/firefox' ff:${ff_version} \
    firefox -print https://google.com -print-footer-left left -print-footer-right right -print-mode pdf -print-file /home/firefox/google.pdf
done
```

**Comment by eclipxe13** [comment]
Ok, I just reproduce the bug and I found it, there is a problem with `unwriteableMargin{Top,Left,Bottom,Right}` and `margin{Top,Left,Bottom,Right}`, let me do more testing

**Comment by bdurrow** [comment]
I are these arguments going override the existing header/footer system or work independently?  If it is helpful to anyone else here is the code I use to handle headers and footers now by modifying the prefs.js before calling firefox (this doesn't work for me in firefox 11; I'm not sure why).

```
ff_setpref() {
  if grep -q "^user_pref(\"$1\", "; then
    sed -i'' -Ee "s,^user_pref\(\"$1\"\,.*$,user_pref\(\"$1\"\, \"$2\"\);," ~/.mozilla/firefox/*.default/prefs.js
  else
    echo "user_pref(\"$1\", \"$2\");" >> ~/.mozilla/firefox/*.default/prefs.js
  fi
}

#Setup Headers and Footers
if [ -n ${HEADER_LEFT+x} ]; then
  ff_setpref "print.print_headerleft" "${HEADER_LEFT-}"
fi
if [ -n ${HEADER_CENTER+x} ]; then
  ff_setpref "print.print_headercenter" "${HEADER_CENTER-}"
fi
if [ -n ${HEADER_RIGHT+x} ]; then
  ff_setpref "print.print_headerright" "${HEADER_RIGHT-}"
fi

if [ -n ${FOOTER_LEFT+x} ]; then
  ff_setpref "print.print_footerleft" "${FOOTER_LEFT-}"
fi
if [ -n ${FOOTER_CENTER+x} ]; then
  ff_setpref "print.print_footercenter" "${FOOTER_CENTER-}"
fi
if [ -n ${FOOTER_RIGHT+x} ]; then
  ff_setpref "print.print_footerright" "${FOOTER_RIGHT-}"
fi
```

**Comment by eclipxe13** [comment]
I just publish a new release, this should be available soon in the addons mozilla website.

Check this information in the README file https://github.com/eclipxe13/cmdlnprint#about-paper-size-edges-and-margins

This is a command you can use to test it:

```
rm /tmp/sample.pdf
firefox -print http://example.org -print-header yes -print-header-left "HEADER LEFT" -print-header-center "HEADER CENTER" -print-header-right "HEADER RIGHT" -print-footer yes -print-footer-left "FOOTER LEFT" -print-footer-center "FOOTER CENTER" -print-footer-right "FOOTER RIGHT" -print-mode pdf -print-file /tmp/sample.pdf
```
Add `-jsconsole -print-info yes` and check the information in the console.

Please, let me know how it works, remember that you have now margin and edge. I tested and both are independant from each other, so you could set different margins and edges for better results.

**Comment by bdurrow** [comment]
I think it would be helpful to document how these arguments interact with the user preference headers and footers.  For instance I would expect that -print-footer no would turn off the footer no matter how it is defined but this is not how it works.  My testing revealed these results:

user pref | on/off argument | text argument | result
----------|-----------------|---------------|--------
set | null | anything including null | footer from user pref
set | off | anything including null | footer from user pref
set | on | null | footer from user pref
set | on | "" | no footer printed
set | on | "NON EMPTY TEXT" | footer from command line

(null means the argument is not included in the command line)
(tested with footer-left)

**Comment by eclipxe13** [comment]
how about this:

- include "on/off" as current "yes/no", "y/n" and "0/1" possible values for booleans
- -print-header (bool)
    - false: set left, center and right as empty strings
    - true: use the values of each preference
    - missing argument or invalid: take it as yes
- -print-header-left (string)
    - missing argument: take it as "user-defined"
    - "user-defined": take the value from the user preferences
    - any other string, including empty "": use this value

These rules apply for header/footer and left/center/right arguments

Examples:

- `firefox -print http://example.org`
    will take all the defaults
- `firefox -print http://example.org -print-footer no`
    will take all the defaults for header but will not produce any footer
- `firefox -print http://example.org -print-footer no -print-header-center '' -print-header-right '2017-03-01'`
    will print header, header left will be the user preference, header center will be an empty string, header right will be the date 2017-03-01
- `firefox -print http://example.org -print-header no -print-footer no`
    will not print header or footer

**Comment by bdurrow** [comment]
You are describing a change in behavior, correct?

**Comment by eclipxe13** [comment]
Yes, just a confirmation of how it should work before making the changes. If you agree then tomorrow I can code it and submit a new version to addons.mozilla.com.

**Comment by bdurrow** [comment]
I think this is much more clear than it is now.  I have a few suggestions if you would consider them:

If you call it a boolean in the documentation I would personally expect true/false to work.

I don't know that this one adds any value:
> "user-defined": take the value from the user preferences

**Comment by eclipxe13** [comment]
`user-defined` would be a special keyword, if it says "user-defined" then will take it from the preferences (in example `user_pref("print.print_footerleft", "");`).

It does not need to be `user-defined`, I think that the text `user_pref` is more specific but less user friendly. And this is just to differentiate from empty strings.

Anyhow, if you _need_ to print the text "user_pref" in some part of the header or the footer you can simply add a leading or trail white space, like `-print-header-left "user_pref "`

**Comment by bdurrow** [comment]
I understand but it doesn't solve any problem I can think of.  If I don't want to over-ride the user-defined preference then I would just omit the argument.  I don't have a strong opinion about it but thought I would offer up my opinion about if it was worth the extra logic.

Another small point, if the user hasn't taken any action these values are defined and this may be confusing.

I like your clever work around if I need user-defined or user_pref.

**Comment by eclipxe13** [comment]
Oh, is not about expecting the user to run `-print-header-left user_pref`, as you say, it will simply avoid the parameter, but what really happens here is that I **requiere** a string to define the content.

So, in the weird case that somebody want to print the word "user_pref" and see other text instead, this is the explanation.

Technically, the first step is to read the parameters from command line, I can have, by example, a null value defining that the argument was not set. But the second step is to pass this parameters **as strings** to a window, and in this point I cannot pass null. I could add another 6 options but to the window but I really don't feel comfortable with it.

OK, have to sleep, tomorrow I will try to implement the changes as defined. Thanks for your feedback and ideas.

**Comment by eclipxe13** [comment]
Uhm, I just realize that the default value of -print-header or -print-footer is defined is "no" (false). If I change it then I could break some existing implementations. So, I will not change the default value for these two options only.

The examples would be:

- `firefox -print http://example.org`
    will not print any header or footer
- `firefox -print http://example.org -print-header yes`
    will take all the defaults for header but will not produce any footer
- `firefox -print http://example.org -print-header yes -print-header-center '' -print-header-right '2017-03-01'`
    will print header, header left will be the user preference, header center will be an empty string, header right will be the date 2017-03-01, will not print any footer.

**Comment by bdurrow** [comment]
Did these features work and experience a regression?  If you are worried about breaking things the change in behavior is likely going to break as much as changing the default value.

**Comment by eclipxe13** [comment]
Finally I couldn't sleep, would you please take a look in the changes? The branch is "next-version".

You can [download the xpi](https://github.com/eclipxe13/cmdlnprint/releases/download/v1.0.4/cmdlnprint_1.0.4.xpi) or you can biuld it `cd src/ ; make build ; make install`.

/me disconnects

**Comment by brailateo** [comment]
I confirm, page headers and footers are working, tested on the example.org and on my own HTML's.
Congratulations, it's an excellent extension, Firefox works slower than libreoffice with -headless but the results are better.
Teo

**Comment by bdurrow** [comment]
If there are headers and footers defined in prefs.js and you call with no head/footer arguments the default action has changed.  In 1.0.3 there were header and footers; in 1.0.4 there are none.
