### ISSUE TITLE
cmdlnprint does not work with Linux Firefox version 45 (ESR)

### ISSUE THREAD

**Issue by bdurrow** [eclipxe13/cmdlnprint#9]
I use docker to test.  I will include my Dockerfile, entrypoint.sh and build commands below.

### Setup x11 forwarding like this:
```
xhost +local:docker && socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"
```

### Run commands are as follows(for each of 11,45,51 set ff_version below):
```
ff_version=<AS MENTIONED ABOVE>
ff_home=`pwd`/ff-home-${ff_version}
DOCKER_DISPLAY=<IP ADDRESS OF WORKSTATION RUNNING X>:0
mkdir ${ff_home}
#Verify version
docker run --rm --volume ${ff_home}:/home/firefox -e "DISPLAY=${DOCKER_DISPLAY}" -u `id -u` -e 'HOME=/home/firefox' ff:${ff_version} firefox -version
#Setup cmdlnprint after running this next command
docker run --rm --volume ${ff_home}:/home/firefox -e "DISPLAY=${DOCKER_DISPLAY}" -u `id -u` -e 'HOME=/home/firefox' ff:${ff_version} firefox
#Now the actual test
docker run --rm --volume ${ff_home}:/home/firefox -e "DISPLAY=${DOCKER_DISPLAY}" -u `id -u` -e 'HOME=/home/firefox' ff:${ff_version} firefox -print https://google.com -print-mode pdf -print-file /home/firefox/google.pdf
```
### Results:
Mozilla Firefox 11.0 on ubuntu precise: PDF Produced
Mozilla Firefox 45.0.2 on ubuntu xenial: cmdlnprint windows displays but hangs
Mozilla Firefox 51.0.1 on ubuntu xenial: PDF Produced

In Firefox 45 I have confirmed that I can print to file in this same environment that cmdlnprint does not work.  I printed to /home/firefox/mozilla.pdf and verified that the output was as expected.

I have tested in a similar manner with the same results with CentOS if you need me to prepare Dockerfile for CentOS I can do so but it would require some work to prepare from the version that I have for my solution.

### Dockerfile
```
FROM ubuntu:latest
#FROM ubuntu:precise
#For Firefox Version 11 use precise (12.04)
#Ubuntu Current Stable is 16.04 aka xenial aka latest

ENV DEBIAN_FRONTEND noninteractive
ENV RUNUSER firefox
ENV UBUNTU_NICKNAME xenial
#ENV UBUNTU_NICKNAME precise
ARG FIREFOX_VERSION=51

RUN \
  useradd -m $RUNUSER && \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_NICKNAME} multiverse" >> /etc/apt/sources.list.d/multiverse.list  && \
  echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_NICKNAME}-updates multiverse" >> /etc/apt/sources.list.d/multiverse.list && \
  echo "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_NICKNAME}-backports restricted universe multiverse" >> /etc/apt/sources.list.d/multiverse.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    dbus-x11 \
    firefox=${FIREFOX_VERSION}* \
    ttf-mscorefonts-installer \
    xvfb && \
  rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /tmp/entrypoint.sh
RUN chmod 755 /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]
```

### entrypoint.sh
```
#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DISPLAY=${DISPLAY-}
FB_DIR=${FB_DIR-/tmp/bigchart-fb}
FB_RESOLUTION=${FB_RESOLUTION-1024x768}
FB_PIXEL_DEPTH=${FB_PIXEL_DEPTH-24}

if [[ -n ${DISPLAY} ]]; then
  echo "DISPLAY already set to ${DISPLAY}.  Skipping Xvfb setup."
else
  echo "Setting up Xvfb in ${FB_DIR}"
  Xvfb :1 -screen 0 ${FB_RESOLUTION}x${FB_PIXEL_DEPTH} -fbdir ${FB_DIR} 2>&1 | \
    egrep -v '^(_XSERVTransmkdir.*will not be created\.|Xlib: extension "RANDR" missing on display .*\.)$' &
  export DISPLAY=":1"
fi

exec "$@"
```

### Build Commands
```
docker rmi ff:11 ff:45 ff:51
docker build --build-arg FIREFOX_VERSION=45 -t ff:45 ./ &&
docker build --build-arg FIREFOX_VERSION=51 -t ff:51 ./ &&
sed -i.orig -E -e 's,^(FROM ubuntu:|ENV UBUNTU_NICKNAME ).*,\1precise,' Dockerfile &&
docker build --build-arg FIREFOX_VERSION=11 -t ff:11 ./
mv Dockerfile.orig Dockerfile
```

**Comment by bdurrow** [comment]
If you prefer I can replicate the results in Vagrant using the virtualbox provider which should be more similar Ubuntu Live in virtualbox that I have read you use as a test environment.

**Comment by eclipxe13** [comment]
@bdurrow Thanks!

It would be great if based on your work we can make a testing/building routine. Even include it on travis-ci or another continious integration service.

I think you are more experienced than me on this matter so If you have the time and willing to help this project you are welcome to make a pull request.

Anyhow, I will try to reproduce your docker setup on my development environment and post the building instructions.

**Comment by bdurrow** [comment]
It looks like the current master addresses this issue; I see travis is currently building with FF 45 and passing.

**Comment by bdurrow** [comment]
Still failing in my test environment with this error logged in the jsconsole:

> Exception { message: "Component returned failure code: 0x…", result: 2152202247, name: "NS_ERROR_GFX_PRINTER_DOC_IS_BUSY", filename: "chrome://cmdlnprint/content/mininav…", lineNumber: 397, columnNumber: 0, data: null, stack: "delayedPrintPageLoadComplete@chrome…", location: XPCWrappedNative_NoHelper } mininav.js:399:9


I'm running like this:
```
Brads-9350:docker brad$ docker run --rm --volume `pwd`/cmdlnprint_shared/:/home/firefox/shared -e "DISPLAY=$DOCKER_DISPLAY" cmdlnprint:45 firefox -jsconsole -print https://google.com -print-mode pdf -print-file /home/firefox/shared/output/google-45.pdf
DISPLAY already set to 192.168.62.240:0.  Skipping Xvfb setup.
Calling firefox -jsconsole -print https://google.com -print-mode pdf -print-file /home/firefox/shared/output/google-45.pdf...
```

**Comment by eclipxe13** [comment]
Checkout new docker files
